FROM golang:1.25.0-alpine3.22

RUN go install github.com/air-verse/air@v1.62.0

WORKDIR /hiven

COPY ../app/go.mod ../app/go.sum ./

RUN go mod download

COPY ../app ./

ENV DB_HOST=postgres-db
ENV DB_USER=postgres
ENV DB_PASSWORD=postgres
ENV DB_NAME=HivenDB
ENV DB_PORT=5432
ENV DB_SSLMODE=disable

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
