FROM golang:1.25.0-alpine3.22

RUN go install github.com/air-verse/air@v1.62.0

WORKDIR /hiven

COPY ../app/go.mod ../app/go.sum ./

RUN go mod download

COPY ../app ./

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
